---

- name: 'Setup local partitioning for a RAID encrypted Ubuntu install'
  hosts: localhost
  connection: local
  handlers:
    - name: 'reload udev'
      command: 'udevadm settle'

    - name: 'reload systemd'
      systemd:
        daemon_reload: true
  vars_files:
    - 'vars/main.yml'
  tasks:
    - name: 'Include disk partition creation logic'
      include_tasks: 'tasks/create_disk_partitions.yml'
      loop: "{{ disks }}"
      loop_control:
        loop_var: _disk

    - name: 'Flush handlers to inform the kernel of the new partitions'
      meta: 'flush_handlers'

    - name: 'Create arrays'
      command: >-
        mdadm --create /dev/{{ item['name'] }}
        --level {{ item['level'] }}
        --raid-devices {{ item['devices'] | length }}
        --metadata {{ item['metadata'] | default('1.2') }}
        {{ ' '.join(item['devices']) }}
      loop: "{{ raid_arrays }}"

    - name: 'Create LUKS devices'
      luks_device_reloaded:
        name: "{{ item.name }}"
        device: "{{ item.device }}"
        state: 'opened'
        keyfile: "{{ item.keyfile }}"
        type: "{{ item.type | default(omit) }}"
      loop: "{{ luks_devices }}"
