---

- name: 'Setup local partitioning for a RAID encrypted Ubuntu install'
  hosts: localhost
  connection: local
  handlers:
    - name: 'reload udev'
      command: 'udevadm settle'

    - name: 'reload systemd'
      systemd:
        daemon_reload: true
  vars_files:
    - 'vars/main.yml'
  tasks:
    - name: 'Close LUKS devices'
      luks_device_reloaded:
        name: "{{ item.name }}"
        state: 'absent'
      loop: "{{ luks_devices }}"

    - name: 'Remove existing arrays'
      command: "mdadm --stop /dev/{{ item['name'] }}"
      when: ansible_facts['devices'][item['name']] is defined
      loop: "{{ raid_arrays }}"

    - name: 'Flush handlers to inform the kernel of the new partitions'
      meta: 'flush_handlers'

    - name: 'Include disk partition erasure logic'
      include_tasks: 'tasks/delete_disk_partitions.yml'
      loop: "{{ disks }}"
      loop_control:
        loop_var: _disk
