---

- name: 'Setup local partitioning for a RAID encrypted Ubuntu install'
  hosts: localhost
  connection: local
  handlers:
    - name: 'reload udev'
      command: 'udevadm settle'

    - name: 'reload systemd'
      systemd:
        daemon_reload: true
  vars_files:
    - 'vars/main.yml'
  tasks:
    - name: 'Include LUKS devices deletion logic'
      include_tasks: 'tasks/delete_luks_device.yml'
      loop: "{{ luks_devices }}"
      loop_control:
        loop_var: _luks_device

    - name: 'Remove existing arrays'
      include_tasks: 'tasks/delete_array.yml'
      when: ansible_facts['devices'][_array['name']] is defined
      loop: "{{ raid_arrays }}"
      loop_control:
        loop_var: _array

    - name: 'Flush handlers to inform the kernel of the new partitions'
      meta: 'flush_handlers'

    - name: 'Include disk partition erasure logic'
      include_tasks: 'tasks/delete_disk_partitions.yml'
      loop: "{{ disks }}"
      loop_control:
        loop_var: _disk
