---

- name: 'Create the LUKS keyfile directory'
  file:
    path: "{{ keyfile_path }}"
    state: 'directory'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: 'Copy the keyfiles to the keyfile directory'
  copy:
    src: "keyfiles/{{ item.keyfile }}"
    dest: "{{ keyfile_path }}/{{ item.keyfile }}"
    force: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  loop: "{{ luks_devices }}"

- name: 'Create LUKS devices'
  luks_device_reloaded:
    name: "{{ item.name }}"
    device: "{{ item.device }}"
    state: 'opened'
    keyfile: "{{ keyfile_path }}/{{ item.keyfile }}"
    type: "{{ item.type | default(omit) }}"
  loop: "{{ luks_devices }}"
