---

- name: "Create partition '{{ _partition.name }}'"
  parted:
    device: "{{ _device }}"
    name: "{{ _partition['name'] | default(omit) }}"
    label: "{{ _partition['label'] | default('gpt') }}"
    part_start: "{{ _partition['part_start'] | default(omit) }}"
    part_end: "{{ _partition['part_end'] | default(omit) }}"
    part_type: "{{ _partition['part_type'] | default(omit) }}"
    unit: "{{ _partition['unit'] | default(omit) }}"
    flags: "{{ _partition['flags'] | default(omit) }}"
    number: "{{ _partition_number + 1 }}"
    state: 'present'
  when: '_device in disks'
  notify: ['reload udev', 'reload systemd']
  loop: "{{ _partition['devices'] }}"
  loop_control:
    loop_var: _device
