---

- name: "Figure out if {{ _luks_device['name'] }} is opened"
  stat:
    path: "/dev/mapper/{{ _luks_device['name'] }}"
  register: _is_luks

- name: "Delete LUKS device {{ _luks_device['name'] }}"
  luks_device_reloaded:
    device: "{{ _luks_device['device'] }}"
    state: 'absent'
  when: _is_luks.stat.exists | bool

- name: "Delete LUKS keyfile path"
  file:
    path: "{{ keyfile_path }}"
    state: 'absent'
  run_once: true

- name: "Delete crypttab file"
  file:
    path: "{{ keyfile_path }}"
    state: 'absent'
  when: keyfile_path | default(false, true) != false
